import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import api from '@/utils/api';
import { toast } from 'sonner';
import { FileText, DollarSign, TrendingUp, LogOut, LayoutDashboard, QrCode, UserPlus } from 'lucide-react';

const AgentDashboard = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [agent, setAgent] = useState(null);
  const [leads, setLeads] = useState([]);
  const [qrData, setQrData] = useState(null);
  const user = JSON.parse(localStorage.getItem('user') || '{}');

  useEffect(() => {
    fetchAgentData();
  }, []);

  const fetchAgentData = async () => {
    try {
      // Get agent by user ID
      const agentResponse = await api.get(`/agents/by-user/${user.id}`);
      console.log('Agent response:', agentResponse.data);
      
      const agentData = agentResponse.data;
      setAgent(agentData);
      
      // Fetch QR code data
      try {
        const qrResponse = await api.get(`/qr/data/${agentData.id}`);
        console.log('QR response:', qrResponse.data);
        setQrData(qrResponse.data);
      } catch (qrError) {
        console.error('QR code fetch failed:', qrError);
      }
      
      // Fetch all leads created by this agent
      const leadsResponse = await api.get('/leads');
      console.log('Leads response:', leadsResponse.data);
      const agentLeads = leadsResponse.data.filter(l => l.source_id === agentData.id);
      setLeads(agentLeads || []);
    } catch (error) {
      console.error('Failed to load agent data:', error);
      toast.error('Agent profile not found. Please register as an agent first.');
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    navigate('/login');
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 flex items-center justify-center">
        <div className="text-lg text-slate-600">Loading dashboard...</div>
      </div>
    );
  }

  const totalLeads = leads.length;
  const convertedLeads = leads.filter(l => l.status === 'disbursed').length;
  const pendingLeads = leads.filter(l => ['new', 'contacted'].includes(l.status)).length;
  const totalCommission = agent?.performance?.total_commission || 0;

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100">
      <nav className="bg-white border-b border-slate-200 px-6 py-4 flex justify-between items-center sticky top-0 z-50">
        <div className="flex items-center gap-3">
          <LayoutDashboard className="w-6 h-6 text-primary" />
          <h1 className="text-2xl font-bold" style={{ fontFamily: 'Manrope, sans-serif' }}>Agent Dashboard</h1>
        </div>
        <div className="flex items-center gap-4">
          {agent?.agent_code && (
            <span className="text-sm bg-primary/10 text-primary px-3 py-1 rounded-full font-medium">
              {agent.agent_code}
            </span>
          )}
          <span className="text-sm text-slate-600">Welcome, {user.full_name}</span>
          <Button
            onClick={() => navigate('/agent/create-lead')}
            className="bg-primary text-primary-foreground hover:bg-primary/90"
            data-testid="create-lead-btn"
          >
            <UserPlus className="w-4 h-4 mr-2" />
            Create Lead
          </Button>
          <Button
            onClick={handleLogout}
            variant="ghost"
            className="text-slate-600"
            data-testid="logout-btn"
          >
            <LogOut className="w-4 h-4 mr-2" />
            Logout
          </Button>
        </div>
      </nav>

      <div className="px-6 md:px-12 lg:px-24 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-12">
          <Card className="hover-lift" data-testid="stat-total-leads">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Leads</CardTitle>
              <FileText className="h-4 w-4 text-primary" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{totalLeads}</div>
              <p className="text-xs text-slate-600 mt-1">Generated by you</p>
            </CardContent>
          </Card>

          <Card className="hover-lift" data-testid="stat-converted-leads">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Converted</CardTitle>
              <TrendingUp className="h-4 w-4 text-primary" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{convertedLeads}</div>
              <p className="text-xs text-slate-600 mt-1">Disbursed loans</p>
            </CardContent>
          </Card>

          <Card className="hover-lift" data-testid="stat-pending-leads">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Pending</CardTitle>
              <FileText className="h-4 w-4 text-accent" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{pendingLeads}</div>
              <p className="text-xs text-slate-600 mt-1">In progress</p>
            </CardContent>
          </Card>

          <Card className="hover-lift" data-testid="stat-commission">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Commission</CardTitle>
              <DollarSign className="h-4 w-4 text-primary" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">₹{totalCommission.toLocaleString()}</div>
              <p className="text-xs text-slate-600 mt-1">All time earnings</p>
            </CardContent>
          </Card>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          {qrData && (
            <Card data-testid="qr-code-card">
              <CardHeader>
                <CardTitle>Your QR Code</CardTitle>
                <CardDescription>Share this to generate leads</CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col items-center">
                <img
                  src={qrData.qr_image_base64}
                  alt="Agent QR Code"
                  className="w-48 h-48 border-2 border-slate-200 rounded-lg"
                  data-testid="qr-code-image"
                />
                <p className="mt-4 text-sm text-slate-600 text-center">
                  Agent Code: <span className="font-bold text-primary">{qrData.agent_code}</span>
                </p>
                <div className="mt-4 w-full space-y-2">
                  <div className="flex gap-2">
                    <Button
                      onClick={() => {
                        navigator.clipboard.writeText(qrData.qr_url);
                        toast.success('Link copied!');
                      }}
                      variant="outline"
                      className="flex-1"
                      size="sm"
                    >
                      Copy Link
                    </Button>
                    <Button
                      onClick={() => window.open(`/api/qr/generate/${agent.id}`, '_blank')}
                      className="flex-1 bg-primary text-primary-foreground"
                      size="sm"
                    >
                      <QrCode className="w-4 h-4 mr-1" />
                      Download
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          <Card className="md:col-span-2" data-testid="quick-stats-card">
            <CardHeader>
              <CardTitle>Performance Overview</CardTitle>
              <CardDescription>Your lead generation statistics</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-sm text-slate-600">Conversion Rate</span>
                  <span className="font-semibold">
                    {totalLeads > 0 ? ((convertedLeads / totalLeads) * 100).toFixed(1) : 0}%
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-slate-600">Active Leads</span>
                  <span className="font-semibold">{leads.filter(l => !['disbursed', 'rejected'].includes(l.status)).length}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-sm text-slate-600">Rejected Leads</span>
                  <span className="font-semibold text-red-600">{leads.filter(l => l.status === 'rejected').length}</span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <Card data-testid="all-leads-card">
          <CardHeader>
            <CardTitle>All Your Leads ({leads.length})</CardTitle>
            <CardDescription>Track all leads you've generated</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {leads.length > 0 ? (
                leads.map((lead) => (
                  <div
                    key={lead.id}
                    className="flex justify-between items-center p-4 bg-slate-50 rounded-lg hover:bg-slate-100 transition-colors"
                    data-testid={`lead-item-${lead.id}`}
                  >
                    <div>
                      <p className="font-medium">{lead.full_name}</p>
                      <p className="text-sm text-slate-600">{lead.mobile} | {lead.requirement}</p>
                      <p className="text-xs text-slate-500 mt-1">Created: {new Date(lead.created_at).toLocaleDateString()}</p>
                    </div>
                    <div className="text-right">
                      <span className={`text-sm px-3 py-1 rounded-full capitalize ${
                        lead.status === 'disbursed' ? 'bg-green-100 text-green-800' :
                        lead.status === 'rejected' ? 'bg-red-100 text-red-800' :
                        lead.status === 'approved' ? 'bg-blue-100 text-blue-800' :
                        'bg-yellow-100 text-yellow-800'
                      }`}>
                        {lead.status.replace('_', ' ')}
                      </span>
                    </div>
                  </div>
                ))
              ) : (
                <div className="text-center py-12 text-slate-500">
                  <FileText className="w-12 h-12 mx-auto mb-4 opacity-50" />
                  <p className="text-lg font-medium mb-2">No leads yet</p>
                  <p className="text-sm mb-4">Start by creating your first lead or sharing your QR code</p>
                  <Button
                    onClick={() => navigate('/agent/create-lead')}
                    className="bg-primary text-primary-foreground"
                  >
                    <UserPlus className="w-4 h-4 mr-2" />
                    Create Your First Lead
                  </Button>
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default AgentDashboard;
